//go:build ignore

package main

import (
	"crypto/rand"
	"fmt"
	"log"
	"os"
)

func main() {
	key := make([]byte, 32) // 256 bits for AES-256
	if _, err := rand.Read(key); err != nil {
		log.Fatalf("failed to generate random key: %v", err)
	}

	file, err := os.Create("keys.go")
	if err != nil {
		log.Fatalf("failed to create keys.go file: %v", err)
	}
	defer file.Close()

	_, err = fmt.Fprintf(file, `// Code generated by go generate; DO NOT EDIT.

package main

// MasterKey is a randomly generated AES key.
var MasterKey = %#v
`, key)
	if err != nil {
		log.Fatalf("failed to write to keys.go file: %v", err)
	}
}
